Fix model version description update in UI
Current behavior:
Request to `https://mlflow.modiface.com/ajax-api/2.0/preview/mlflow/model-versions/update` fails with status code 500.
Server error:

... protobuf/json_format.py", line 732, in _ConvertScalarFieldValue
    if _UNPAIRED_SURROGATE_PATTERN.search(value):
TypeError: expected string or bytes-like object  

Caused by version not being passed as a string.

Proposed fix: stringify version, in the same way that's done in `handleStageTransitionDropdownSelect`