Pin uvloop<0.22 to fix mlserver compatibility
uvloop 0.22 introduced breaking changes that cause RuntimeError when
mlserver worker processes attempt to get the event loop. This pins
uvloop to versions below 0.22 to maintain compatibility.

Fixes mlserver worker initialization failures with error:
RuntimeError: There is no current event loop in thread 'MainThread'.

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>