Fix online_config dict deserialization in scoring jobs
When OnlineScorer objects are serialized to dicts for job submission,
the nested online_config dataclass is converted to a dict. When
reconstructing OnlineScorer objects from these dicts, we need to
explicitly convert the online_config dict back to an OnlineScoringConfig
object.

This fixes the error: 'dict' object has no attribute 'sample_rate'

Signed-off-by: dbczumar <corey.zumar@databricks.com>