Fix `train_predict.py` (#670)
Running the tensorflow example via `python tensorflow/train_predict.py` results in the following error:
```                        
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/boston_housing.npz
57344/57026 [==============================] - 0s 1us/step
INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpqza4q6ig
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpqza4q6ig', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7efc62095128>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
Traceback (most recent call last):
  File "tensorflow/train_predict.py", line 54, in <module>
    tf.app.run(main=main)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow/train_predict.py", line 25, in main
    with tracking.start_run() as tracked_run:
AttributeError: module 'mlflow.tracking' has no attribute 'start_run'
```

It seems that the `start_run` function has been moved from `mlflow.tracking` to `mlflow`. This pull request simply changes `with tracking.start_run() as tracked_run:` to `with mlflow.start_run() as tracked_run:`.