Update compatibility with later versions of pyarrow (up to 0.17.0)
- Remove hdfs3 support because current code fails with pyarrow 0.17.0
"TypeError: connect() got an unexpected keyword argument 'driver'"

- Related arrow commit where hdfs3 is deactivated
(see https://github.com/apache/arrow/commit/4e53749097ba687afd5e000067925def2e2802c9)

- Setting ARROW_PRE_0_15_IPC_FORMAT=1 in tests for spark udf:
https://spark.apache.org/docs/latest/sql-pyspark-pandas-with-arrow.html#compatibiliy-setting-for-pyarrow--0150-and-spark-23x-24x

- Even though the tests have been updated it still keeps working with older pyarrow versions, driver will just take 'libhdfs' as default arg