updates to pull request train_predict.py (#946)
MLproject updated (removed tags_constants; renamed to 'hidden-units')
train_predict.py updated per feedback comments; however, hardcoded mandatory tf_meta_graph_tags to avoid tensorflow error:
TypeError: log_model() missing 1 required positional argument: 'tf_meta_graph_tags=[tf.saved_model.tag_constants.SERVING]'