Use float64 so that `mlflow models predict` can be used on the trained model.
Addressing
mlflow.exceptions.MlflowException: dtype of input float64 does not match expected dtype float32
which gets otherwise produced for a JSON input.

Signed-off-by: Jan Pazdziora <jpazdziora@redhat.com>